### ISSUE TITLE
Column information in the result

### ISSUE THREAD

**Issue by silviucpp** [mysql-otp/mysql-otp#100]
Hello,

Currently the library returns `{ok, ColumnNames, Rows}` as response to a select. I think will be useful to return instead `ColumnNames` a tuple `{ColumnName, ColumnType}`. I found this useful when you want to transform different data types like tinyint into atoms (true/false).

**Comment by zuiderkwast** [comment]
It would be possible, but it would change the interface. Perhaps it can be controlled by configuration or separate function.

Your use case is not very convincing to me. It doesn't seem like the right way to do things. :smile: In general, a TINY_INT is a one byte integer, not just 0 and 1. It's better to convert to boolean only where each query is performed so that you know when to expect a boolean, based on what you know about the data.

Also, if I remember correctly, we don't always get a very exact type from MySQL. For several types, we just get VARCHAR or TEXT for various types such as for SET, ENUM, GEOMETRY etc. so it's not very reliable.

**Comment by silviucpp** [comment]
I found a better way to convert them so you can forget about this request.
