### ISSUE TITLE
otp 21.0 influence 

### ISSUE THREAD

**Issue by GeraldXv** [mysql-otp/mysql-otp#109]
> Erlang/OTP version R16B or later, excluding 21.0 which has a bug in binary pattern matching. This was fixed in OTP 21.1.

As we are using otp 21.0 and mysql-otp, I want to confirm if the main influence is about TimeStamp?

**Comment by zuiderkwast** [comment]
Yes, well, it was a bug in binary pattern matching introduced in 21.0 and fixed in 21.1. If you run the tests on otp 21.0 you will see exactly what fails. I think it was affecting the decoding of dates, datetime, possibly other types as well.

If you want to rewrite the decoding to use a workaround which works on otp 21.0, I'm happy to merge it, as long as it's simple and efficient.

**Comment by zuiderkwast** [comment]
OTP bug report: https://bugs.erlang.org/browse/ERL-689

OTP fix: https://github.com/erlang/otp/pull/1911

**Comment by GeraldXv** [comment]
I just pull a new request: https://github.com/mysql-otp/mysql-otp/pull/110.
Pls review it ~~

**Comment by GeraldXv** [comment]
As some issues, I just create a new request: https://github.com/mysql-otp/mysql-otp/pull/112.
Pls review the new one.
