### ISSUE TITLE
We must add reconnect strategy

### ISSUE THREAD

**Issue by iloveai8** [mysql-otp/mysql-otp#140]
server start,but mysq restart eg:google rds Unscheduled restart,so server down.

**Comment by zuiderkwast** [comment]
Reconnect is not for the same connection, because it would loose its internal state. The framework outside can reconnect by starting a new connection. There are various to use a backoff strategy in supervisor or worker pool, for example https://github.com/fishcakez/backoff_supervisor#backoff_supervisor and https://github.com/pouriya-jahanbakhsh/director.

**Comment by iloveai8** [comment]
@zuiderkwast i konw you!i mean: we can try reconnect in the my_conn process, like this 
handle_info({tcp_closed, _Socket}, State) ->
    try_reconnect(tcp_closed, State#state{ping_ref = undefined});
handle_info({tcp_error, _Socket, Reason}, State) ->
   stop_server({tcp_error, Reason}, State);

or

handle_info({'DOWN', _MRef, _, Pid, _Info}, State) ->
     try_reconnect(tcp_closed, State);

**Comment by zuiderkwast** [comment]
I known it's possible, but it's bad. See https://github.com/mysql-otp/mysql-otp/issues/22#issuecomment-125165013.

**Comment by iloveai8** [comment]
Thank you for your answer1
