### ISSUE TITLE
MariaDB broken

### ISSUE THREAD

**Issue by zuiderkwast** [mysql-otp/mysql-otp#154]
I tried running the tests on MariaDB 10.3.15 today. It crashes on the handshake.

```
$ make tests
 GEN    test-dir
 GEN    eunit
======================== EUnit ========================
module 'mysql'
  module 'mysql_tests'
    mysql_tests: connect_synchronous_test...*skipped*
undefined
*unexpected termination of test process*
::{old_server_version,
      [{mysql_protocol,verify_server_capabilities,2,
           [{file,"src/mysql_protocol.erl"},{line,491}]},
       {mysql_protocol,build_handshake_response,5,
           [{file,"src/mysql_protocol.erl"},{line,461}]},
       {mysql_protocol,handshake,7,
           [{file,"src/mysql_protocol.erl"},{line,85}]},
       {mysql_conn,handshake,1,[{file,"src/mysql_conn.erl"},{line,193}]},
       {mysql_conn,'-connect/1-fun-0-',2,[{file,[...]},{line,...}]}]}
```

I think this broke after merging #152 where a capability was added to the handshake, which wasn't there before. Ping @juhlig

**Comment by juhlig** [comment]
Not sure I can check back before next year.

But, judging from the stacktrace, it crashes in `verify_server_capabilities/2`. On a guess, this may be because I added the `CLIENT_LONG_PASSWORD` flag on the side (line 499 in `mysql_protocol`), the MySQL docs say it is assumed to be said since $VERY_OLD_VERSION.

If you want to take a stab at it, my first try would be to remove that flag again (or, maybe it should be better placed among the client flags).

**Comment by zuiderkwast** [comment]
Yes, I got that it's CLIENT LONG PASSWORD, but I didn't think of moving it to add_client_capabilities. It should do. Thanks!

**Comment by zuiderkwast** [comment]
Thanks for the helping me close this fast!

With this in mind, we should probably prioritize having some test jobs for MariaDB in Travis.
