### ISSUE TITLE
Setting the {keep alive,true} option causes potential errors

### ISSUE THREAD

**Issue by dong50252409** [mysql-otp/mysql-otp#161]
first execute `mysql:query(Conn,Sql).`

But now it's triggered 
`handle_info(ping, #state{socket = Socket, sockmod = SockMod} = State) ->
    setopts(SockMod, Socket, [{active, false}]),
    Ok = mysql_protocol:ping(SockMod, Socket),
    setopts(SockMod, Socket, [{active, once}]),
    {noreply, update_state(Ok, State)};`
Ok overrides the process state data

execute `mysql:affected_rows(pid)`  will not get the right results

**Comment by juhlig** [comment]
Ok, I see the problem :) Same goes for `insert_id`.

@zuiderkwast what do you think? I'll have to investigate a little further about what pinging may or may not do to server status and warning count, but on the face of it I'd say it should be quite safe to just reschedule the ping instead of updating the state.

**Comment by juhlig** [comment]
Ok, I checked what is inside the `OK` packet that answers the ping. As I expected, it also changes the status and warning counts, so this should be ignored also. As status, warning count, affected rows and insert id is all there is in an `OK` packet, and the response to `COM_PING` is _always_ an `OK` packet, I think it is safe and best to just ignore it and just reschedule the ping.

**Comment by zuiderkwast** [comment]
Good catch! I totally agree.

**Comment by zuiderkwast** [comment]
Fixed by #162.
