### ISSUE TITLE
What’s meaning of `server_name_indication`?

### ISSUE THREAD

**Issue by wwhai** [mysql-otp/mysql-otp#164]
I found a SSL option named `server_name_indication` but I don’t known it’s meaning.Please publish a document for ssl configuration . Thanks.

**Comment by juhlig** [comment]
The SSL options in mysql-otp are passed to [ssl:connect/3](http://erlang.org/doc/man/ssl.html#connect-3) in order to upgrade the TCP socket to SSL (the first variant of connect/3 in the documentation), they are not specific to mysql-otp. Thus, I would refer you to the [documentation for the `ssl` application in Erlang](http://erlang.org/doc/man/ssl.html).

That said, SNI is mainly of use for virtual hosting (simply, multiple virtual hosts under one IP address) in order to let a server know which virtual hosts the client wants to access _before_ the SSL connection is established (again simply, to know which is the right certificate to send). You can read more about how it works and why it is necessary in virtual hosting [here](https://en.wikipedia.org/wiki/Server_Name_Indication).

I suggest just leaving it at the default, ie not giving it in the SSL options at all. I have no idea if it has any impact for a connection to a MySQL server, since it has no virtual hosting capabilities to begin with. I guess SNI is more or less ignored, but I don't know.
Now, the documentation for `ssl:connect/2,3` says that `server_name_indication` _should_ be given when `{verify, verify_peer}` is given, so there _may_ be a problem (in which case, please give us some feedback in this ticket), which should be solved by either disabling `server_name_indication` or giving the same host as in the options given to `mysql:start_link/1`.

**Comment by zuiderkwast** [comment]
Refer to the ssl documentation for Erlang/OTP: https://erlang.org/doc/man/ssl.html

In short, `server_name_indication` serves two purposes:

1. Makes the client send SNI to the server in the client hello, so that the server can choose a certificate based on this.
2. Enables host name checking when checking the certificate received from the server. `{verify, verify_peer}` makes the client check not only that the certificate is signed by a trusted CA but also that the identity of the certificate (a subjectAltName field or the CN in the Subject field in the certificate) is that of the requested service, that is, matching the value used for SNI. This is to prevent man-in-the-middle attacks.

    If `{verify, verify_peer}` is given but `server_name_indication` is not given, the server IP is required as an identity in the certificate in subjectAltName, which possible but it's not how you generally create certificates.

    To disable the identity check, pass `{server_name_indication, false}`. Note that this is not the same as leaving out the `server_name_indication` option altogether.

(There may be improvements possible to mysql-otp here, i.e. passing the name given in start_link to ssl....)

**Comment by juhlig** [comment]
>        If `{verify, verify_peer}` is given but `server_name_indication` is not given, the server IP is required as an identity in the certificate in subjectAltName, which possible but it's not how you generally create certificates.

It is worth mentioning that mysql-otp adds this (`{verify, verify_peer}`) by itself if `verify` is not given in the ssl options.

>        To disable the identity check, pass `{server_name_indication, false}`. Note that this is not the same as leaving out the `server_name_indication` option altogether.

I think it is supposed to be `disable`, not `false`.

> (There may be improvements possible to mysql-otp here, i.e. passing the name given in start_link to ssl....)

Yeah, I think that as we add `{verify, verify_peer}`, we should then set sni along with it accordingly (if absent).

**Comment by zuiderkwast** [comment]
> It is worth mentioning that mysql-otp adds this (`{verify, verify_peer}`) by itself if verify is not given in the ssl options.

Oops! I wasn't aware of that.

> I think it is supposed to be `disable`, not `false`.

Of course. Edited comment above.

> Yeah, I think that as we add {verify, verify_peer}, we should then set sni along with it accordingly (if absent).

Yes, totally! Except if host is a tuple (i.e. an IP address). We should also describe that we do verify peer by default, since it's not the default in Erlang/OTP ssl.

**Comment by wwhai** [comment]
> The SSL options in mysql-otp are passed to [ssl:connect/3](http://erlang.org/doc/man/ssl.html#connect-3) in order to upgrade the TCP socket to SSL (the first variant of connect/3 in the documentation), they are not specific to mysql-otp. Thus, I would refer you to the [documentation for the `ssl` application in Erlang](http://erlang.org/doc/man/ssl.html).
> 
> That said, SNI is mainly of use for virtual hosting (simply put, multiple virtual hosts under one IP address) in order to let a server know which virtual hosts the client wants to access _before_ the SSL connection is established (again simply put, to know which is the right certificate to send). You can read more about how it works and why it is necessary in virtual hosting [here](https://en.wikipedia.org/wiki/Server_Name_Indication).
> 
> I suggest just leaving it at the default, ie not giving it in the SSL options at all. I have no idea if it has any impact for a connection to a MySQL server, since it has no virtual hosting capabilities to begin with. I guess SNI is more or less ignored, but I don't know.
> Now, the documentation for `ssl:connect/2,3` says that `server_name_indication` _should_ be given when `{verify, verify_peer}` is given, so there _may_ be a problem (in which case, please give us some feedback in this ticket), which should be solved by either disabling `server_name_indication` or giving the same host as in the options given to `mysql:start_link/1`.

Thanks for your answer!I understand it.

**Comment by zuiderkwast** [comment]
Thanks @wwhai for raising the question!

Regarding the improvement discussed with @juhlig, I think we shall add a default `{server_name_indication, Host}` when `is_list(Host) andalso inet_parse:domain(Host)` so that we only send it if it's a domain name. Only domain names, not IP addresses, are not allowed in SNI. A PR is welcome.

**Comment by juhlig** [comment]
> Only domain names, not IP addresses, are not allowed in SNI.

Hm, I don't think that is strictly true. According to the documentation of `ssl:connect/3` (the upgrade-a-TCP-socket-to-SSL variant), if `verify_peer` is set and `server_name_indication` is absent, it will default to sending the (string form of) the IP address. I also found out that it is indeed possible to issue certificates for IP addresses, though this is rarely done, and no actual CA (that I know of) does it.

> A PR is welcome.

Already prepared one, just didn't get it fully finished yet ;)

> Regarding the improvement discussed with @juhlig, I think we shall add a default `{server_name_indication, Host}` when `is_list(Host) andalso inet_parse:domain(Host)` so that we only send it if it's a domain name.

I did it slightly different:
If `Host` is a list, and `inet:parse_address/1` (I didn't use `inet_parse`, as this module is undocumented and therefore likely an internal thing) does not return an `ok` tuple, `server_name_indication` defaults to `Host`. From an outside perspective, this is what `ssl:connect/2,3` does if you were using it to connect an SSL socket directly (vs upgrading).
If `Host` is something else (ie, an IP address, either in tuple or string form, or an atom like `loopback`), `server_name_indication` defaults to `disable`. This is different from what `ssl` does, but I think it is what is usually intended. If you think it better to stick to the `ssl` behavior (ie, not setting any default and let `ssl` decide what to send), it's no trouble changing that.

**Comment by juhlig** [comment]
#166

**Comment by zuiderkwast** [comment]
> > Only domain names, not IP addresses, are not allowed in SNI.

> Hm, I don't think that is strictly true. According to the documentation of ssl:connect/3 (the upgrade-a-TCP-socket-to-SSL variant), if `verify_peer` is set and `server_name_indication` is absent, it will default to sending the (string form of the) IP address. I also found out that it is indeed possible to issue certificates for IP addresses, though this is rarely done, and no actual CA (that I know of) does it.

No, now you didn't read the documentation carefully enough. :-)

The ssl option `server_name_indication` is used for two things: One is sending SNI to the server. The other is using this name when checking the identities in the server's certificate.

If `server_name_indication` is absent, SNI is *not* sent to the server in handshake hello, but the certificate is checked and the IP is required to be present in subjectAltName.

If `server_name_indication` is `disable`, SNI is also not sent to the server and no check for DNS name nor IP is done for the certificate. Only chain of trust is checked.

Btw, it is totally valid to use self-signed certificates and to have your own CA within a company, etc., something that can be used e.g. between a database and application.

Look at https://1.1.1.1/ for an example of using IP address as identity in the certificate.

**Comment by juhlig** [comment]
> No, now you didn't read the documentation carefully enough. :-)

Ah, my bad, you're totally right :)
In that case, it would indeed be the best to default sni to the hostname only if it is a non-IP string, and otherwise not set any default sni and, in the absence of any sni option from the user, just let ssl do whatever ssl does in such a case.
