### ISSUE TITLE
calculated value(float) returned as binary.

### ISSUE THREAD

**Issue by q1208c** [mysql-otp/mysql-otp#182]
I am new guy for Erlang.
Recently, I use Erlang write a own project with MySQL.
mysql-otp is the connector.
When I SELECT value that calculated by MySQL, the value returned as binary, not float.

The SQL:
-----------------------------------
        SELECT
            ?,
            col_material_type,
            col_food_id,
            col_food_value * ? / rl.col_recipe_weight,
            ?
        FROM
            tb_recipe_detail AS rd,
            tb_recipe_list AS rl
        WHERE
            rd.col_recipe_id = rl.col_recipe_id
                AND rd.col_recipe_id = ?
-----------------------------------
The results:
-----------------------------------
 [[1,1448,0,1857,<<"150.00000000">>,0],
  [1,1448,0,1287,<<"100.00000000">>,0],
  [1,1448,0,1204,<<"1.00000000">>,0],
  [1,1448,0,1193,<<"6.00000000">>,0],
  [1,1448,0,1178,<<"6.00000000">>,0],
  [1,1448,0,1108,<<"1.00000000">>,0],
  [1,1448,0,1091,<<"20.00000000">>,0],
  [1,1448,0,940,<<"3.00000000">>,0],
  [1,1448,0,889,<<"100.00000000">>,0],
  [1,1448,0,839,<<"3.00000000">>,0],
  [1,1448,0,838,<<"3.00000000">>,0]]
-----------------------------------

Maybe I use the wrong function, or method.

Sorry for my poor English.

**Comment by zuiderkwast** [comment]
That's interesting. DECIMAL(P,S) is binary only if P >= 16. Maybe it's because there is some multiplication and division in the query, so the server sends it as a higher precision decimal. The client only knows what's sent in the protocol.

I think you can just convert it with `binary_to_float()`. Please re-open the issue if you need more help.
