### ISSUE TITLE
mysql_protocol:recv_packet(...) returns {error, closed} that unhandled in mysql_protocol:fetch_response.

### ISSUE THREAD

**Issue by erlscript** [mysql-otp/mysql-otp#196]
![vs8JzNZcXX](https://user-images.githubusercontent.com/25943938/163172880-23c6b830-1193-4eab-b212-54991056c05d.jpg)

**Comment by erlscript** [comment]
It's an occasionally triggerd error, I don't know how to exactly trigger this, maybe a connection that have not been used for a while will close or something?

**Comment by zuiderkwast** [comment]
It's by design, the so call "let it crash" principle for unexpected cases. See this comment: https://github.com/mysql-otp/mysql-otp/pull/173#pullrequestreview-602041624

Pull request #173 is a proposal to make this error message look a bit nicer. The last that happened was that I had some comments that were not addressed. (I wanted `exit(...)` to happen in mysql_conn, not in mysql_protocol.) Feel free to finish that change (make another PR based on that one).
