### ISSUE TITLE
{error,close}

### ISSUE THREAD

**Issue by ZARAPACK** [mysql-otp/mysql-otp#202]
Hello, about the {error, close} error in mysql_otp running. This error mainly occurs when my erlang server node hangs in the background for a night and I execute two sql statements in a short period of time. This problem does not occur when the server is just started.
![image](https://github.com/mysql-otp/mysql-otp/assets/48713519/aab1b5b4-ffe6-4628-bc27-cde95c98f66b)

**Comment by Maria-12648430** [comment]
Hm, connections closing, due to timeouts and whatnot, can be somewhat expected I'd say. But in such a case, the `mysql_conn` process should detect it and exit, not hang around until you try to use it again and only _then_ find out that the connection was closed :thinking:

**Comment by Maria-12648430** [comment]
Ah... @zuiderkwast, look, may that be it?

https://github.com/mysql-otp/mysql-otp/blob/5b999ca8da878c18281d5efe2ff98212d51ac6d3/src/mysql_conn.erl#L556-L561

There are clauses for `tcp_closed` and `tcp_error`, but none for `tcp`. The connection gets set to `{active, once}` after each _client-initiated_ communication with the server. But if the server at some point sends a TCP message by itself, like, unasked for, it will be ignored, which may be ok to do, but the connection will go to `{active, false}` state, and not notice any connection-closing events etc.

I _also_ see that there are no clauses at all for `ssl`/`ssl_closed`/`ssl_error`, so if it is a TLS connection, connection-closing events won't be noticed at all.

**Comment by zuiderkwast** [comment]
Hi @ZARAPACK and @Maria-12648430,

`exit` when the server closes the connection is expected, yes, but it shouldn't crash like this. It's not very nice.

If the server closes the connection due to inactivity, it closes the TCP connection (it sends a TCP FIN or RST) and then the process would get a `{tcp_closed, _Socket}` message to `handle_info`. But I don't think that's the case here.

If the server connection is broken and the server had no chance to close the connection (e.g. network broken), the client believes it is open until it tries to use it, and then gen_tcp:send or gen_tcp:recv returns `{error, closed}`.

The stack trace mentions badmatch in `mysql_protocol:prepare/3`, and there we find this:

```erlang
prepare(Query, SockModule, Socket) ->
    Req = <<?COM_STMT_PREPARE, (iolist_to_binary(Query))/binary>>,
    {ok, SeqNum1} = send_packet(SockModule, Socket, Req, 0),
    {ok, Resp, SeqNum2} = recv_packet(SockModule, Socket, SeqNum1),
    ...
```

gen_tcp:recv/2 returns `{error, closed}` if the server is gone/unreachable, and that's a bad match here.

I think this return value is handled in `mysql_protocol:query/N` and `mysql_protocol:execute/N` since #201 was merged (just recently) but obviously not in `mysql_protocol:prepare/3`. It probably should, so the process can exit gracefully in this case too.

We have this design that the process dies when the connection is lost. As what I've understood, it is not generally the prefered way to do things in Erlang. Maybe we should actually change that and do reconnects and release that as 2.0.

@Maria-12648430 regarding `ssl_closed` and `ssl_error`, well spotted that there is no case for them! We need to add that. Regarding `tcp`, it is only for data and we don't expect any data when we haven't sent any query to the server, so I doubt it's needed. We could add a case for it anyway though, since it would indicate the protocol is out of sync.

**Comment by juhlig** [comment]
> We have this design that the process dies when the connection is lost. As what I've understood, it is not generally the prefered way to do things in Erlang. Maybe we should actually change that and do reconnects and release that as 2.0.

No, I don't think we should, at least not transparently and/or as a default.

All session state (temporary tables, variables, transactions) will be lost on disconnect, and if a reconnect happens without the user being informed of the disconnect, he will assume that he is still in the session he has been working with, with all the session-bound stuff still there.

AFAIK, it is for mainly this reason that most database clients which once sported auto-reconnect abilities (for Erlang and other languages, for MySQL and other databases) removed it without replacement. Better offload/leave it in the hands of the user if and how he wants to handle disconnects I'd say :grin:
If disconnectes happen, it may be expected. OTOH, there may be something a little wrong, and getting worse. With automated reconnects, the latter would be totally glossed over, until the proverbial pot boils over and all hell breaks loose :stuck_out_tongue_closed_eyes:

**Comment by zuiderkwast** [comment]
>> Maybe we should actually change that and do reconnects and release that as 2.0.
>
> No, I don't think we should, at least not transparently and/or as a default.
>
> All session state (temporary tables, session variables, transactions) will be lost on disconnect,

@juhlig I'm aware of that. That's why I always argued that we're doing the right thing when we exit on close and on network failures. However, this is not considered nice OTP worker style. If the client is under a supervisor, the database is down and sync connect is used, the restart limit is quickly reached and causes the whole supervision tree to go down. You've probably heard the story.

If the state can be recreated, by forcing all state to be created using options like `{queries, [...]}` and `{prepare, [...]}` and possibly some new on-connect callback function, and by requiring the users to use the provided transaction functions rather than explicit `BEGIN`, etc., it could be a better experience for users.

It's probably best to keep the default though, as you way, and do reconnect only if explicitly requested (an option).

> If disconnectes happen, it may be expected. OTOH, there may be something a little wrong, and getting worse. With automated reconnects, the latter would be totally glossed over, until the proverbial pot boils over and all hell breaks loose :stuck_out_tongue_closed_eyes:

I'm not sure I see what you're talking about here. Of course we won't do reconnect on failures. Only when the database/network comes and goes.
