### ISSUE TITLE
not match {error, close}

### ISSUE THREAD

**Issue by aposto** [mysql-otp/mysql-otp#22]
```erlang
start_link() at <0.142.0> exit with reason {{{case_clause,{error,closed}},[{mysql_protocol,fetch_response,5,[{file,"src/mysql_protocol.erl"},{line,303}]},
{mysql,execute_stmt,4,[{file,"src/mysql.erl"},{line,763}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,607}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,639}]},
{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_server,call,[<0.124.0>,{execute,log_ccu_stmt,[0,0,0]},infinity]}} in context child_terminated
```
not match {error, close}

**Comment by zuiderkwast** [comment]
`start_link` crashing in this situation is normal I would say. Which behaviour are you expecting?

**Comment by ronalfei** [comment]
@zuiderkwast  , I think this error will be occur when a mysql connectiong was broken, so I expect this gen_server should reconnect mysqld when mysql gen_server receive a tcp down message.

**Comment by ronalfei** [comment]
reconnect is very important especially when you use mysql-otp-poolboy

**Comment by evbogdanov** [comment]
Good news, everyone! @aposto @ronalfei, you can create a simple gen_server that deals with disconnects:
```erlang
%%%-----------------------------------------------------------------------------
%%% State :: {disconnected, Opts} | {Conn, Opts}
%%%-----------------------------------------------------------------------------
%%% Conn  :: pid()
%%%-----------------------------------------------------------------------------
%%% Opts  :: [{host, Host}, {user, User}, ...]
%%%-----------------------------------------------------------------------------
-module(myapp_mysql_conn).

-behaviour(gen_server).

-export([
    % api
    start_link/1,
    % gen_server callbacks
    init/1,
    handle_call/3,
    handle_cast/2,
    handle_info/2,
    terminate/2,
    code_change/3
]).

%%%=============================================================================
%%% api
%%%=============================================================================

start_link(Opts) ->
    gen_server:start_link({local, ?MODULE}, ?MODULE, Opts, []).

%%%=============================================================================
%%% gen_server callbacks
%%%=============================================================================

init(Opts) ->
    process_flag(trap_exit, true),
    {ok, {disconnected, Opts}}.

handle_call(conn, _From, {disconnected, Opts}) ->
    case mysql:start_link(Opts) of
        {ok, Conn}     -> {reply, {ok, Conn}, {Conn, Opts}};
        {error, Error} -> {reply, {error, Error}, {disconnected, Opts}}
    end;

handle_call(conn, _From, {Conn, Opts}) ->
    {reply, {ok, Conn}, {Conn, Opts}};

handle_call(_Request, _From, State) ->
    {reply, ok, State}.

handle_cast(_Request, State) ->
    {noreply, State}.

handle_info({'EXIT', Conn, _}, {Conn, Opts}) ->
    {noreply, {disconnected, Opts}};

handle_info(_Info, State) ->
    {noreply, State}.

terminate(_Reason, _State) ->
    ok.

code_change(_OldVsn, State, _Extra) ->
    {ok, State}.

```

**Comment by zuiderkwast** [comment]
A process corresponds to a connection. When the connection is broken, the state associated with the connection is lost. That is prepared statements, mysql session variables, etc. If it would reconnect automatically, you would not see that these are lost. Therefore it is the correct behaviour that it crashes.

If you're using a connection pool you normally shouldn't have to worry about this. If a connection crashes, poolboy (or similar) will create another one and add it to the pool.

If you want a reconnection connection, you can do as @evbogdanov suggest or better: You can use a regular supervisor which is the standard way to restart a crashing process.

**Comment by ronalfei** [comment]
thank for reply!
Yes, a simple gen_server can resolve my problem without poolboy. but ,I want use mysql-otp-poolboy to build my application.
so  set the keepalive config  cannot resolve my problem too.
because when a connection disconnected, the gen_server mysql can not feeling, so the process will alive, and poolboy can't restart this process.
so that when a request come in,  and client checkout a process with broken connection, the error will be occur. this will lead to user request failed.

another way to resolve this problem is set {active, true} to the connection socket in default  , set {active , false} when the connection checkout, and set {active , true} when it checkin.

The process will receive a messsage like {tcp, closed} when it bind a connection socket in {active, true} state. so that  mysql gen_server will receive this message by handle_info, it can return a exit state and  supervisor will restart the process actively, then everything is fine.

but I don't know Is this way will lower the throughtput or not?

**Comment by ionuthristodorescu** [comment]
I get this error message in CentOS 7 a lot, but not on Mac OS. Any ideas why ?

**Comment by zuiderkwast** [comment]
@ionuthristodorescu I don't know.

**Comment by zuiderkwast** [comment]
In general, this is a TCP related problem. If the server disconnects, it sends a TCP close (or FIN) message, but if the server crashes or the network gets disconnected, there is no TCP close message. In this case, there is no way to know that the connection is gone until we try to send or receive something.

**Comment by juhlig** [comment]
> In general, this is a TCP related problem. If the server disconnects, it sends a TCP close (or FIN) message, but if the server crashes or the network gets disconnected, there is no TCP close message. In this case, there is no way to know that the connection is gone until we try to send or receive something.

While this cannot be solved to receive something instantly when the connection is gone because of a server crash or network failure, it can be changed to be noticed earlier by tuning some TCP raw options, namely the keepalive time, probes, and interval. The defaults (on a linux system) are insanely high (IMO): keepalive time defaults to 2 hours, probes to 9, interval to 75 seconds. So the first keepalive probe is sent only after the connection was idle for 2 hours, and then it sends 8 more probes with a 75 seconds delay in between before it decides the connection is dead. I usually tune those down to 300s keepalive time, 3 probes, 30s delay, but what actual good values are depends on your environment. Also, the raw option numbers for them may be different on different OSes.

**Comment by zuiderkwast** [comment]
So, how does an Erlang process get noticed about the TCP close instantly in active mode then? I guess it must be using the same mechanisms, isn't it?

**Comment by juhlig** [comment]
No, not really, I believe.

When a connection is closed normally, the closing end sends some TCP packet (FIN or RST or something, don't remember) to the other end to tell it the connection is closing. This is more or less handled at the OS level, so is not restricted to Erlang stuff, and it does that regardless of how the process that had the connection closes it itself, or just terminates, normally or by crash.

On the other hand, if the machine at one end crashes or the network goes down, it is too late to send anything indicating connection close. The connection just falls silent on the other end.

In Erlang in active mode, it "actively" waits for stuff coming down the connection. If it receives something, it transforms that into an appropriate message, which will be `{tcp_close, ...}` in the case of a connection close packet. In case of the connection just "vanishing", even active mode won't notice instantly. It is only after the keepalives kick in (or the connection is otherwise used, eg with application-level pings or heartbeats) that it being gone is detected.

This is probably a bit over-simplified, but that's more or less how it works ;)
