### ISSUE TITLE
can not reconnect when a mysqld disconnect

### ISSUE THREAD

**Issue by ronalfei** [mysql-otp/mysql-otp#25]
It's will be make error when execute a query, like #22

**Comment by zuiderkwast** [comment]
This is the correct behaviour.

If you want to know in advance that a connection has crashed, you should use the keepalive option so that the connection is checked at regular intervals. By default, MySQL server closes the connection after 8 hours of inactivity, so setting the keepalive to 7 hours could solve your problem.

**Comment by zuiderkwast** [comment]
Perhaps the keepalive feature should be enabled by default in a future version.

**Comment by zuiderkwast** [comment]
Related: #33
