### ISSUE TITLE
binary <->

### ISSUE THREAD

**Issue by snailman** [mysql-otp/mysql-otp#51]
Hello,
First, thanks for this repo.  i want to store a record  into the BLOB column, and then  read  back from mysql  as a record. how can i do this? thx

**Comment by johlo** [comment]
You should use [term_to_binary/1](http://erlang.org/doc/man/erlang.html#term_to_binary-1) to create a binary representation of the record, then write that binary as your BLOB value.
When reading it back from the mysql db apply [binary_to_term/1 ](http://erlang.org/doc/man/erlang.html#binary_to_term-1) on the value from the database to get the Erlang record again.

**Comment by KoFish** [comment]
@snailman: I hope I'm wrong in this but I would like to propose that you probably do not want to do that. johlos suggestion will probably work fine since a records are just represented by a tuple in erlang (tagged with the records name). This means that you any change to the record length will crash the program when you read an old "record" from the DB and then try to treat it as a record.

**Comment by johlo** [comment]
Yes, @KoFish is right, if the record definition is changed any old values in the DB needs to be migrated to the new format before using it.
There are a few different ways of handling the evolution of records when serializing the records as binary blobs. 
I have typically added an additional `version` field in the record definition and when reading data from the DB treated them as tuples (using `erlang:element/2` to access the fields) and creating a new tuple that matches the latest record definition.

Another way could be to create a tuple list like [{field1, value}, {field2,value}, ...] and serialize that using `term_to_binary/1`, basically the same thing since you still have to manually create the new tuple which matches the record definition.

**Comment by snailman** [comment]
thx all，i got it

**Comment by johlo** [comment]
@snailman great! Can you please close this issue, thanks.
