### ISSUE TITLE
How to skip checking statements  in prepare config

### ISSUE THREAD

**Issue by newsdy** [mysql-otp/mysql-otp#54]
hi, i use mysql-otp with a pool named pooler, url:https://github.com/seth/pooler

a question occured as that:
    the pooler call mysql:start_link() and get the pid of mysql connection, the example config is that:
```
{pooler, [
           {pools, [
                    [{name, logger_pool},
                     {max_count, 50},
                     {init_count, 20},
                     {start_mfa,
                      {mysql, start_link, [[{host,"127.0.0.1"}, {port, 3306}, {user, "mycomm"}, {password, "mycomm123"}, {database, "c8config"},
                                            {prepare,
                                             [
                                              {'heartbeat.select', "select 1 from dual"}
                                             ]
                                            }
                                           ]]}}]
                   ]}
          ]}
```

when the statements are wrong, such as unknown column, mysql-otp throw an error of badmatch in 

```
Prepare = proplists:get_value(prepare, Options, []),
            lists:foreach(fun ({Name, Stmt}) ->
                              {ok, Name} = mysql:prepare(Pid, Name, Stmt)
                          end,
                          Prepare);
```

`pool 'logger_pool' failed to start member:{error,{'EXIT',{{badmatch,{error,{1054,<<"42S22">>,<<"Unknown column 'work_start_time11' in 'where clause'">>}}},[{mysql,'-start_link/1-fun-1-',2,[{file,"/root/workspace/cti_dialing_svr_test/_build/default/lib/mysql/src/mysql.erl"},{line,163}]},{lists,foreach,2,[{file,"lists.erl"},{line,1336}]},{mysql,start_link,1,[{file,"/root/workspace/cti_dialing_svr_test/_build/default/lib/mysql/src/mysql.erl"},{line,162}]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,330}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,355}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,607}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,639}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}}}`

Pooler thought the connection was created failed, but mysql connection was created success.
I have a timer to execute stmt, so pooler always created a new connection.After a while the mysql connections reached the upper limit.
Use `show processlist` in mysql
I think it's not Pooler's fault, right?
What should I do? thx

**Comment by ingwinlu** [comment]
the gen_server that got startet should probably be closed when creating the prepared stmt's fail. I will add a testcase and a fix.

**Comment by ingwinlu** [comment]
I am however a bit surprised that is even a problem. Since the sql handler gets spawned via start_link and the calling process does crash due to the badmatch it should kill the connection as well.

**Comment by newsdy** [comment]
But i found the connection was still exist in mysql db with the cmd `show processlist`  @ingwinlu 
Is it my fault? i used pooler and mysql-otp, i will test mysql-otp alone

**Comment by newsdy** [comment]
Fix it? thx

**Comment by juhlig** [comment]
Hm, I think I see the problem.

> I am however a bit surprised that is even a problem. Since the sql handler gets spawned via start_link and the calling process does crash due to the badmatch it should kill the connection as well.

That is not necessarily the case, in fact I should be surprised if it was so. Failure to start any worker should definitely _not_ crash a pool (`poolboy` has that problem, my PR for this is still pending), so `pooler` will be catching that, assuming "if there is no pid returned, well, there is no worker". So the `pooler` pool will not crash, and thus the linked mysql process won't, either (this is just a guess as I'm not familiar with `pooler`, but an educated one). 

So, I'd say the fault lies clearly within `mysql-otp` for creating a connection process but not returning the pid because of the subsequent failure (or not killing the connection process, for that matter).

@zuiderkwast, what do you think? As I see it, we could...
1. keep quiet about the query/prepare failures, and just always return the pid. This is of course not good (not knowing what was done and what wasn't, not even knowing there _was_ anything wrong), I'm only mentioning it for completeness' sake.
2. `exit(Pid, kill)` if something unexpected is returned from `query` or `prepare`, and return the error tuple as usual. Using kill has the charm that it is instant and untrappable, so the connection process is certain to be killed. The catch is that this will then propagate to the calling process (since it is already linked to the connection process at the time the post-connect queries/prepares are run) and cause them to exit as well. To avoid this, the calling process should either set to trap exits temporarily, or the connection process must be started unlinked and be linked later when the post-connect stuff has succeeded and the process has thus not been killed.
3. same as (2), but use `mysql:stop(Pid)` instead of `exit(Pid, kill)`. I'm not 100% certain about the guarantees that gives (via `gen_server:stop` etc) about really exiting the process, but I would assume it is fairly certain, on par with `exit(Pid, kill)`. A possible problem is that this is synchronous, so it may cause delays where they are not necessary. For that reason, I would call `mysql:stop` from a spawned process and be done with it, let it take its time to exit, however long it takes.
4. same as (3), but do the entire post-connect stuff in a `spawn_monitor`ed process, then wait for the `'DOWN'` message. If the down reason is `normal`, all is well and we return the pid, if it is something else, there was an error and we return an error tuple. The spawned process should link the connection process before it does anything, so if _anything_  goes wrong, the connection process is sure to be crashed, too, so we don't even have to do any manual killing etc.

**Comment by juhlig** [comment]
We could also move the post-connect stuff inside the connection process... Now that I think about it, this is probably the best solution...

**Comment by zuiderkwast** [comment]
@juhlig Thanks for explaining the problem! I didn't really get it until now: start_link throws an exception even though the process is already spawned and linked.

I think suggestion 3 seems fine. `start_link` is synchronous, including all the post-connect stuff, so it seems right that also the stopping is done synchronously.

To move the post-connect stuff inside the connection process, so that the exception occurs before the `init` returns, seems even more correct. If it can be done in a simple and clean way, this is what I prefer.

**Comment by juhlig** [comment]
Hm, just looked into it. While I, too, would prefer moving it into `init`, it will require some restructuring, like factoring out some of the query and prepare code from the respective `handle_call` clauses into separate functions so they can be called cleanly from the "inside" as well.

I'll go for my suggestion 3 for now, this is really simple in comparison, and doesn't really put anything in the way of moving things into the connection process later.

**Comment by newsdy** [comment]
Thank you very much, I'll close the issue
