### ISSUE TITLE
boolean atoms encoding

### ISSUE THREAD

**Issue by silviucpp** [mysql-otp/mysql-otp#55]
Hello,

In most of my projects most of the time I need to convert the true | false atoms into 1 or 0 before sending to mysql-otp.

I think will be nice if mysql-opt will do this on it's own. Right now anyway is crashing

Silviu

**Comment by zuiderkwast** [comment]
Hello! It's by design.

There are no booleans in standard SQL or in MySQL. Boolean is just a synonym for tinyint(1). When values are fetched from the database, you always get them as integers.

I think there should be only one unique representation of values and it is integer in this case. That makes documentation and testing and the whole think more simple.

Sorry!
