### ISSUE TITLE
Another mysql:transaction-bug

### ISSUE THREAD

**Issue by emfa** [mysql-otp/mysql-otp#90]
So the last fix did do a lot of good but we still have experienced some weird behaviours (although I think the root is not in the driver). 

However, I've found one more thing that have happened to us in production that might need fixing.

Since the server is oblivious to the client (we never monitor/link to the client. I'm starting to wonder if this should be fixed. In that case the server would know which processes is using it in the current transaction and could thus clean up if something happens to it).

Anyhow, the issue at hand...

The call to gen_server:call(C, start_transaction) is made without a timeout and thus if that call takes more then 5s the client dies with a timeout BUT the start_transaction might still go through. If this happens and if you are using something like poolboy this might(and have) lead to connections being returned to poolboy in an inconsistent state(still in a transaction).

I think the proper way to fix this is to just set timeout to infinity. If timeout is needed that can be imposed from somewhere else. A more elegant way would probably be something along the lines described above with proper monitoring of the clients.

**Comment by zuiderkwast** [comment]
There is a macro for rollback and commit is called `?cmd_timeout` (I think) and is 3s but feel free to increase it. What do you think is appropriate? 30s?

You think for start trancaction we should use infinity? Ok, fine!

I'll accept such a PR.

It's a pity that poolboy is not linking to or monitoring the processes, as would a supervisor, but that's another project. A better pool handling would add the clients to a supervisor so that they are properly supervised, or what do you have in mind?
